const USER_ADMIN = "USER_ADMIN";
const USER_NORMAL = "USER_NORMAL";
const USER_VISITOR = "USER_VISITOR";
const USER_SALES = "USER_SALES";

module.exports = { USER_ADMIN, USER_NORMAL, USER_VISITOR, USER_SALES };
